In [1]:
import pandas as pd
import numpy as np
import math
import sys

In [2]:
data = pd.read_csv('user_cat.csv',index_col=0)
data.head()

C:\Users\tusha\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

   member_id  category_id  group_id  rating
0          3            2    490552    4.67
1        210            2    490552    4.67
2     357518            2    490552    4.67
3     511008            2    490552    4.67
4     915553            2    490552    4.67

In [3]:
data.shape

(3127947, 4)

In [4]:
tester = data.sample(n=1000).copy()
tester.head()

         member_id  category_id  group_id  rating
1878442  203583715           12   1770593    4.47
948715   237206923           31   1896321    3.90
360281   173615702           27   3400072    4.62
170245     7733996           34   1116874    4.63
1334670   62807592           34   5087172    4.84

In [5]:
tester.shape

(1000, 4)

In [6]:
tester['values']=1

In [7]:
df_pivot=tester.pivot_table(index=['member_id'], columns=['category_id'],values='values').fillna(0)
df_pivot.head()

category_id,1,2,3,4,5,6,8,9,10,11,...,26,27,28,29,30,31,32,33,34,36
member_id,,,,,,,,,,,,,,,,,,,,,
66976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
249841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
522395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
967755,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1108564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [8]:
df_pivot.iloc[0:1]

category_id,1,2,3,4,5,6,8,9,10,11,...,26,27,28,29,30,31,32,33,34,36
member_id,,,,,,,,,,,,,,,,,,,,,
66976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [9]:
test_users = df_pivot.iloc[0:5].copy()

In [10]:
test_users

category_id,1,2,3,4,5,6,8,9,10,11,...,26,27,28,29,30,31,32,33,34,36
member_id,,,,,,,,,,,,,,,,,,,,,
66976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
249841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
522395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
967755,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1108564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [11]:
# remaining_users = df_pivot.iloc[1:].copy()

In [12]:
# remaining_users.head()

In [13]:
def pearson_calc(numbers_x, numbers_y):
    if(len(numbers_x)==0):
        mean_x = sum(numbers_x)/0.001
    elif(len(numbers_y)==0):
        mean_y = sum(numbers_y)/0.001
    else:
        mean_x = sum(numbers_x)/len(numbers_x)
        mean_y = sum(numbers_y)/len(numbers_y)
    
#     print('Mean x :', mean_x)
#     print('Mean y :', mean_y)
    subtracted_mean_x = [i - mean_x for i in numbers_x]
    subtracted_mean_y = [i - mean_y for i in numbers_y]

    x_times_y = [a * b for a, b in list(zip(subtracted_mean_x, subtracted_mean_y))]

    x_squared = [i * i for i in numbers_x]
    y_squared = [i * i for i in numbers_y]
    
#     print('X_squared :', x_squared)
#     print('Y_squared :', y_squared)
    
    N = sum(x_times_y)
    D = math.sqrt(sum(x_squared) * sum(y_squared))
    if (D !=0):
        return N/D
    else:
        return N/0.001

In [14]:
def match_cal(user1,user2):
    match = 0
    df_u1 = user1.values.tolist()
    df_u2 = user2.values.tolist()
    df_u1 =  [y for x in df_u1 for y in x] 
    df_u2 =  [y for x in df_u2 for y in x] 
    for i in range(0,len(df_u2)):
        if(df_u2[i]==1 and df_u1[i]==1):
            match=match+1
        else:
            match=match+0.001
#     print('match',match)
    pearson_correlation_val = pearson_calc(df_u1,df_u2)
    return match,pearson_correlation_val

In [15]:
def pearson_score(user1,user2):
    '''
    user1 & user2 : user ids of two users between which similarity score is to be calculated.
    '''
    # A list of categories joined by both the users.
    both_match_count, score = match_cal(user1,user2)
    
#     print('both matches :',both_match_count)
    # Returning '0' if no common values.
    if both_match_count == 0 :
        return 0
    return score

In [16]:
test_users

category_id,1,2,3,4,5,6,8,9,10,11,...,26,27,28,29,30,31,32,33,34,36
member_id,,,,,,,,,,,,,,,,,,,,,
66976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
249841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
522395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
967755,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1108564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [17]:
test_users.index[0]

66976

In [18]:
get_user1 = test_users.index[0]
get_user1 = int(get_user1)
print(get_user1)

66976

In [19]:
# remaining_users.index.summary()

In [20]:
# remaining_users.index.shape

In [21]:
score_per_user_match = []
member_vals = []
index_list = []
for index,row in test_users.iterrows():
    index_list.append(index)

In [22]:
print(index_list)

[66976, 249841, 522395, 967755, 1108564]

In [23]:
# remaining_users.index[0]

In [24]:
one = test_users.iloc[0:1].copy()

In [25]:
two = test_users.iloc[1:2]
two

category_id,1,2,3,4,5,6,8,9,10,11,...,26,27,28,29,30,31,32,33,34,36
member_id,,,,,,,,,,,,,,,,,,,,,
249841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
test_users.iloc[0:5]

category_id,1,2,3,4,5,6,8,9,10,11,...,26,27,28,29,30,31,32,33,34,36
member_id,,,,,,,,,,,,,,,,,,,,,
66976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
249841,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
522395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
967755,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1108564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [27]:
#len(index_list)

In [28]:
vals = one.values.tolist()
flattened_list = [y for x in vals for y in x]

In [29]:
print(flattened_list)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]

In [30]:
scores = []
members1 = []
members2 = []
result = []
for i in range(0,len(index_list)):
#     print('user 1 --',user1)
    members1.append(index_list[i])
    user1 = test_users.iloc[i:i+1]
    for j in range(0,len(index_list)):
        user2 = test_users.iloc[j:j+1]
#         print('user 2 --',user2)
        score = pearson_score(user1,user2)
        scores.append(score)
        members2.append(index_list[j])
        list_add = []
        list_add.append(index_list[i])
        list_add.append(index_list[j])
        list_add.append(score)
        result.append(list_add)

In [31]:
len(members2)

25

In [32]:
members1

[66976, 249841, 522395, 967755, 1108564]

In [33]:
checking = pd.DataFrame(result, columns = ['users_set_1', 'users_set_2','scores']) 
checking

    users_set_1  users_set_2    scores
0         66976        66976  0.969697
1         66976       249841 -0.030303
2         66976       522395 -0.030303
3         66976       967755 -0.030303
4         66976      1108564  0.969697
5        249841        66976 -0.030303
6        249841       249841  0.969697
7        249841       522395 -0.030303
8        249841       967755 -0.030303
9        249841      1108564 -0.030303
10       522395        66976 -0.030303
11       522395       249841 -0.030303
12       522395       522395  0.969697
13       522395       967755 -0.030303
14       522395      1108564 -0.030303
15       967755        66976 -0.030303
16       967755       249841 -0.030303
17       967755       522395 -0.030303
18       967755       967755  0.969697
19       967755      1108564 -0.030303
20      1108564        66976  0.969697
21      1108564       249841 -0.030303
22      1108564       522395 -0.030303
23      1108564       967755 -0.030303
24      1108564      1108564  0.969697

In [34]:
df_pivot_new=checking.pivot_table(index=['users_set_1'], columns=['users_set_2'], values = 'scores').fillna(0)
df_pivot_new

users_set_2   66976     249841    522395    967755    1108564
users_set_1
66976        0.969697 -0.030303 -0.030303 -0.030303  0.969697
249841      -0.030303  0.969697 -0.030303 -0.030303 -0.030303
522395      -0.030303 -0.030303  0.969697 -0.030303 -0.030303
967755      -0.030303 -0.030303 -0.030303  0.969697 -0.030303
1108564      0.969697 -0.030303 -0.030303 -0.030303  0.969697

In [36]:
member_selected = df_pivot_new.ix[66976,0:]
range_df= df_pivot_new.ix[66976:,0:]

C:\Users\tusha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\tusha\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [37]:
member_selected

users_set_2
66976      0.969697
249841    -0.030303
522395    -0.030303
967755    -0.030303
1108564    0.969697
Name: 66976, dtype: float64

In [38]:
range_df

users_set_2   66976     249841    522395    967755    1108564
users_set_1
66976        0.969697 -0.030303 -0.030303 -0.030303  0.969697
249841      -0.030303  0.969697 -0.030303 -0.030303 -0.030303
522395      -0.030303 -0.030303  0.969697 -0.030303 -0.030303
967755      -0.030303 -0.030303 -0.030303  0.969697 -0.030303
1108564      0.969697 -0.030303 -0.030303 -0.030303  0.969697

In [39]:
import sklearn
from sklearn.neighbors import NearestNeighbors

In [40]:
def find_k_neighbours(df,k):
    order = np.argsort(df.values, axis=1)[:, :k]
    df = df.apply(lambda x: pd.Series(x.sort_values(ascending=False).iloc[:k].index, index=['top{}'.format(i) for i in range(1, k+1)]), axis=1)
    return df

In [41]:
neigh_5 = find_k_neighbours(df_pivot_new,5)
neigh_5

                top1     top2    top3    top4    top5
users_set_1
66976        1108564    66976  967755  249841  522395
249841        249841  1108564   66976  522395  967755
522395        522395  1108564   66976  967755  249841
967755        967755  1108564   66976  522395  249841
1108564      1108564    66976  967755  249841  522395

In [42]:
for i in neigh_5.itertuples():
        print(i)

Pandas(Index=66976, top1=1108564, top2=66976, top3=967755, top4=249841, top5=522395)
Pandas(Index=249841, top1=249841, top2=1108564, top3=66976, top4=522395, top5=967755)
Pandas(Index=522395, top1=522395, top2=1108564, top3=66976, top4=967755, top5=249841)
Pandas(Index=967755, top1=967755, top2=1108564, top3=66976, top4=522395, top5=249841)
Pandas(Index=1108564, top1=1108564, top2=66976, top3=967755, top4=249841, top5=522395)

In [61]:
def get_user_groups(selected_user, neigh_5):
    neigh_5 = neigh_5.loc[selected_user]
    selected_users = []
    for i in neigh_5:
#         print(i)
        if(i not in selected_users and (i is not None) ):
            selected_users.append(i)

        else:
            pass
    groups = pd.read_csv("members.csv", encoding='latin-1')
    filter_grp = groups['member_id'].isin(selected_users)
    groups.where(filter_grp,inplace=True)
    groups = groups.dropna()
    final_groups =  pd.read_csv("groups.csv", encoding='latin-1')
    final_groups.merge(groups, on='group_id')
    final_groups.dropna()
    return final_groups
    return groups

In [62]:
selected_user = 66976
disp_df = get_user_groups(selected_user, neigh_5)
disp_df

,group_id,category_id,category.name,category.shortname,city_id,city,country,created,description,group_photo.base_url,...,organizer.photo.photo_link,organizer.photo.thumb_link,organizer.photo.type,rating,state,timezone,urlname,utc_offset,visibility,who
0,6388,14,health/wellbeing,health-wellbeing,10001,New York,US,2002-11-21 16:50:46,Those who practice or hold a strong interest i...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.39,NY,US/Eastern,alternative-health-nyc,-14400,public,Explorers of Health
1,6510,4,community/environment,community-environment,10001,New York,US,2003-05-20 14:48:54,The New York Alternative Energy Meetupis for t...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.31,NY,US/Eastern,alternative-energy-meetup,-14400,public,Clean Energy Supporters
2,8458,26,pets/animals,pets-animals,10001,New York,US,2004-03-27 09:55:41,not_found,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.84,NY,US/Eastern,Animals,-14400,public,Animal Voices
3,8940,29,sci-fi/fantasy,sci-fi-fantasy,10001,New York,US,2002-11-16 04:49:16,Welcome to the The New York City Anime Meetup ...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.46,NY,US/Eastern,NYC-Anime,-14400,public,Anime Fans
4,10104,26,pets/animals,pets-animals,10001,New York,US,2003-10-22 21:39:49,"We welcome those who support pits, even if you...",https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.09,NY,US/Eastern,NYC-Pitbull,-14400,public_limited,"NYC Pits & People, Dog Lovers"
5,10359,16,language/ethnic identity,language,10001,New York,US,2003-05-22 14:19:52,"Hello! Michael Kim 'Jamal' Riegelman, the Dir...",https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.58,NY,US/Eastern,NYCArabicClub,-14400,public_limited,Arabophiles!
6,12111,16,language/ethnic identity,language,10001,New York,US,2002-10-08 17:22:28,NYC ASL is a social/conversation group for Dea...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.46,NY,US/Eastern,NYCASL,-14400,public_limited,NYC ASL Member
7,12542,22,new age/spirituality,new-age-spirituality,10001,New York,US,2002-10-08 17:22:23,Astrology is an amazing tool for self-explorat...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.59,NY,US/Eastern,nyc-astrology,-14400,public,Astrology Buffs
8,12907,28,religion/beliefs,religion-beliefs,10001,New York,US,2002-10-30 03:09:34,WEB: WWW.NYC-ATHEISTS.ORG 212-330-6794\n======...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.63,NY,US/Eastern,atheists-24,-14400,public,Atheists
9,14573,13,movements/politics,government-politics,10001,New York,US,2003-04-14 17:20:41,not_found,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.56,NY,US/Eastern,aynrand-8,-14400,public,Objectivists
10,15217,31,socializing,socializing,10001,New York,US,2003-02-05 02:32:46,This is a freewheeling friendly group of terri...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.34,NY,US/Eastern,TheGreatNYCBackgammonGroup,-14400,public_limited,Happy Rollers
11,15324,23,outdoors/adventure,outdoors-adventure,60601,Chicago,US,2003-10-22 21:39:49,Welcome to the Chicago Backpackers Group\nWhy ...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.79,IL,US/Central,Chicago-Backpackers,-18000,public,Backpackers
12,16620,26,pets/animals,pets-animals,10001,New York,US,2004-08-23 17:18:59,JOIN US for good weather monthly gatherings wh...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.85,NY,US/Eastern,basenji-nyc,-14400,public,Basenji Lovers
13,17183,31,socializing,socializing,10001,New York,US,2003-05-30 02:47:56,"BBFP and Admirers get together to have fun, tr...",https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.58,NY,US/Eastern,bbfp-68,-14400,public_limited,BBFP & Those Who Respect Them
14,17921,26,pets/animals,pets-animals,10001,New York,US,2002-12-23 16:48:09,The Beagle is an amazing dog! These hounds hav...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.73,NY,US/Eastern,beagle-pack,-14400,public,Beagle Lovers
15,18843,5,dancing,dancing,10001,New York,US,2003-06-19 09:53:09,The NYC Bellydance Meetup is the place to go f...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.71,NY,US/Eastern,NYCBellydancers,-14400,public,Bellydancers/Shimmy Sisters
16,20517,33,support,support,10001,New York,US,2003-05-20 01:14:27,So lonely is the road walked alone.\nBitter is...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.66,NY,US/Eastern,bipolar-10,-14400,public_limited,Merry Lunatics
17,22211,11,games,games,60601,Chicago,US,2003-04-17 19:31:25,The Chicagoland area's premiere and largest ga...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.72,IL,US/Central,chicagogames,-18000,public,Gamers
18,22253,11,games,games,10001,New York,US,2003-02-02 22:47:36,We are dedicated to playing board and card gam...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.51,NY,US/Eastern,nyc-boardgames,-14400,public_limited,Gamers
19,23713,18,book clubs,book-clubs,10001,New York,US,2002-10-08 17:22:23,Come join our book exchange to learn more abou...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,3.98,NY,US/Eastern,bookcrossing-30,-14400,public,BookCrossers
20,24765,26,pets/animals,pets-animals,60601,Chicago,US,2003-04-29 20:53:16,Boston Terrier owners who get together to soci...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.53,IL,US/Central,ChicagoBostonTerriers,-18000,public,Boston Terrier Owners
21,25709,16,language/ethnic identity,language,60601,Chicago,US,2003-04-30 20:06:30,Our meetup group is the hottest new after work...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.51,IL,US/Central,Socialize-Network-and-Connect,-18000,public,Professionals
22,25727,16,language/ethnic identity,language,10001,New York,US,2003-04-21 15:55:04,The Brazilian culture meet-up group is a space...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.37,NY,US/Eastern,NYC-BraziliansandBrazilianCulture,-14400,public,Brazilians and friends
23,26154,28,religion/beliefs,religion-beliefs,60601,Chicago,US,2003-10-22 21:39:49,"Here in Chicago, the group meetsevery 4th Mond...",https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.43,IL,US/Central,chicago-freethought,-18000,public_limited,Freethinkers
24,26217,28,religion/beliefs,religion-beliefs,10001,New York,US,2003-10-22 21:39:49,Bright's are people whose ethics and worldview...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.46,NY,US/Eastern,NYCBrights,-14400,public,Brights
25,26415,32,sports/recreation,sports-recreation,10001,New York,US,2002-10-08 17:22:28,Our mission Keeping us connected\nBig Apple Br...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.44,NY,US/Eastern,NYC-British-Expats,-14400,public,Big Apple Brits
26,26434,16,language/ethnic identity,language,94101,San Francisco,US,2002-11-20 00:19:28,Are you formerly of the British Isles or Irela...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.48,CA,US/Pacific,brit-92,-25200,public,Expat British and Irish
27,29051,16,language/ethnic identity,language,60601,Chicago,US,2003-01-28 21:59:35,We are a group of Chicago-based Canadians and ...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.55,IL,US/Central,canadian-37,-18000,public_limited,Chicago's Canadians
28,29074,31,socializing,socializing,10001,New York,US,2002-10-08 17:22:28,Are you a Canadian looking to connect with and...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,4.45,NY,US/Eastern,NYCCanadians,-14400,public,Canadians
29,30077,31,socializing,socializing,10001,New York,US,2004-01-06 05:10:57,"For all games and gaming interests: blackjack,...",https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,5.00,NY,US/Eastern,casino-4,-14400,public,Casino Enthusiasts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16300,26359539,2,career/business,career-business,60601,Chicago,US,2017-10-23 15:20:45,The Chicago Young Real Estate Investors meetup...,not_found,...,not_found,not_found,others,0.00,IL,US/Central,Chicagos-Young-Real-Estate-Investors,-18000,public,Members
16301,26359565,2,career/business,career-business,94101,San Francisco,US,2017-10-23 15:23:41,This meetup is dedicated to the Founders of Fi...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,FinTech-San-Francisco,-25200,public,Members
16302,26359663,34,tech,tech,10001,New York,US,2017-10-23 15:35:48,This group is for founders/ CEOs who are looki...,not_found,...,not_found,not_found,others,0.00,NY,US/Eastern,New-York-Founder-Wellness-Meetup,-14400,public,Members
16303,26359878,34,tech,tech,10001,New York,US,2017-10-23 15:56:17,"This is a Meetup catered towards Finance, Bank...",not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,From-Wall-Street-to-Silicon-Alley,-14400,public,Members
16304,26360738,23,outdoors/adventure,outdoors-adventure,10001,New York,US,2017-10-23 17:16:26,Weather is still great. Let's catch warm and s...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,Outdoors-Art-and-Museums,-14400,public,Members
16305,26360820,28,religion/beliefs,religion-beliefs,60601,Chicago,US,2017-10-23 17:25:41,Catalyzing the international community of Chic...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,IL,US/Central,International-Community-Meetup,-18000,public,Members
16306,26361954,11,games,games,10001,New York,US,2017-10-23 19:15:26,Working on a game? Join us once a month in Dum...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,NYC-Game-Makers,-14400,public,Members
16307,26362623,10,food/drink,food-drink,10001,New York,US,2017-10-23 20:24:23,Let's get together for free and cheap activiti...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,Free-and-cheap-things-to-do-in-the-city,-14400,public,Members
16308,26363602,2,career/business,career-business,10001,New York,US,2017-10-23 22:03:57,This is a group for soul-driven entrepreneurs ...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,Lunar-Hustle-Meetup,-14400,public,Members
16309,26364045,21,music,music,94101,San Francisco,US,2017-10-23 22:48:36,Do you love to see rock shows? Would you like ...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,Rock-Show-Mos,-25200,public,Members
16310,26364471,16,language/ethnic identity,language,60601,Chicago,US,2017-10-23 23:36:02,"I am slow learner in reading and writing, thos...",not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,IL,US/Central,meetup-group-THiZMSuD,-18000,public,Members
16311,26364572,34,tech,tech,94101,San Francisco,US,2017-10-23 23:48:55,Are you interested in learning how Clara Labs ...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,Clara-Hosts-Meetups-Clara-Labs-YC-14,-25200,public,Members
16312,26364624,9,fitness,fitness,60601,Chicago,US,2017-10-23 23:55:05,"People who want to get their healthy goals, lo...",not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,IL,US/Central,MeetUp-Health-Fitness-and-Mindset,-18000,public,"Nutrition, Fitness and Mindset"
16313,26365189,32,sports/recreation,sports-recreation,94101,San Francisco,US,2017-10-24 01:00:06,This Meetup is for anyone who is interested in...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,San-Francisco-Brazilian-Jiu-Jitsu-Meetup,-25200,public,Members
16314,26366221,14,health/wellbeing,health-wellbeing,94101,San Francisco,US,2017-10-24 03:05:16,"We all want to confidently ask for a raise, as...",not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,The-art-of-getting-what-you-want-hacking-fear,-25200,public,Members
16315,26370222,2,career/business,career-business,10001,New York,US,2017-10-24 13:46:32,We will discuss Technology trends including Cy...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,Information-Technology-Lunch-Learn-Lenovo-All-...,-14400,public,Members
16316,26371769,22,new age/spirituality,new-age-spirituality,10001,New York,US,2017-10-24 16:34:09,The Curious Spirit Soul Circles are designed t...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,The-Curious-Spirit-Soul-Circles,-14400,public,Members
16317,26372763,2,career/business,career-business,10001,New York,US,2017-10-24 18:17:53,"This is group to Inspire, ignite, influence an...",https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,luxurylifestyle,-14400,public,Luxury Influencers
16318,26373312,10,food/drink,food-drink,10001,New York,US,2017-10-24 19:12:25,Pears and Bees are for anyone interested in sp...,not_found,...,not_found,not_found,others,0.00,NY,US/Eastern,Pears-and-Bees,-14400,public,Members
16319,26373450,6,education/learning,education-learning,10001,New York,US,2017-10-24 19:23:31,Review and practice GRE topics and questions w...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,meetup-group-hCICaoBf,-14400,public,Members
16320,26373602,34,tech,tech,94101,San Francisco,US,2017-10-24 19:39:55,"Coming soon - an awesome, likeminded group of ...",not_found,...,not_found,not_found,others,0.00,CA,US/Pacific,earndotcom,-25200,public,Members
16321,26374579,20,movies/film,movies-film,10001,New York,US,2017-10-24 21:15:51,This is for any person or company who needs im...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,Digital-Film-Academy-Production-Pitch,-14400,public,Members
16322,26374655,16,language/ethnic identity,language,94101,San Francisco,US,2017-10-24 21:24:18,This is a group for anyone who interested in i...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,Vocabulary-workhop,-25200,public,Members
16323,26375445,31,socializing,socializing,10001,New York,US,2017-10-24 22:50:07,There will be no hair styling at our salons. \...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,NYC-Discussion-Salon,-14400,public,Members
16324,26376543,2,career/business,career-business,60601,Chicago,US,2017-10-25 00:57:35,This is a group looking to network with people...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,IL,US/Central,Successful-Business-Analyst-in-an-Agile-Enviro...,-18000,public,Members
16325,26377464,34,tech,tech,94101,San Francisco,US,2017-10-25 02:45:29,Engineers looking into entrepreneurial opportu...,https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,shinectcommunity,-25200,public,Members
16326,26377698,14,health/wellbeing,health-wellbeing,94101,San Francisco,US,2017-10-25 03:18:46,"Learn how to get what you want in life, love, ...",not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,CA,US/Pacific,Conference-The-art-of-getting-what-you-want-ha...,-25200,public,Members
16327,26378067,9,fitness,fitness,60601,Chicago,US,2017-10-25 04:08:38,Early morning joggers in the Streeterville are...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,IL,US/Central,Streeterville-Running-Group,-18000,public,Members
16328,26378128,23,outdoors/adventure,outdoors-adventure,10001,New York,US,2017-10-25 04:17:08,I think people should dance more in public. Wh...,not_found,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,NY,US/Eastern,Just-Dance-NYC,-14400,public,Dancers
16329,26378470,31,socializing,socializing,60601,Chicago,US,2017-10-25 05:08:23,"Are you looking to exchange, make friends, net...",https://secure.meetupstatic.com,...,https://secure.meetupstatic.com/photos/member/...,https://secure.meetupstatic.com/photos/member/...,member,0.00,IL,US/Central,FREE-Arabic-Chicago-Evanston-North-Burbs,-18000,public,Members

In [63]:
g_list = disp_df['group_id'].to_list()

In [64]:
g_list = set(g_list)
g_list = list(g_list)

In [65]:
print(len(g_list))

16330

In [66]:
c_list = disp_df['category_id'].to_list()
c_list = set(c_list)
c_list = list(c_list)

In [67]:
print(len(c_list))

33